<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Column Element</name>
   <tag></tag>
   <elementGuidId>f20ec25f-7895-46e4-81b2-b0e975129dd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabs-:r0:--tabpanel-2']/div/table/thead/tr/th[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>bd3c316b-37e9-4048-bca4-a85ca4fed9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>bb72ff88-c684-48ee-9de1-98061bcc4c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-6 py-3</value>
      <webElementGuid>dafdf0b4-e920-4a13-b71f-882119fc21ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Element</value>
      <webElementGuid>233f9724-1c0d-4145-802b-b79add1f6407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs-:r0:--tabpanel-2&quot;)/div[@class=&quot;relative overflow-x-auto&quot;]/table[@class=&quot;w-full text-sm text-left&quot;]/thead[@class=&quot;text-base border-b-4 border-light-red&quot;]/tr[1]/th[@class=&quot;px-6 py-3&quot;]</value>
      <webElementGuid>afa117f0-1cc7-4032-bac0-a604e8125814</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs-:r0:--tabpanel-2']/div/table/thead/tr/th[4]</value>
      <webElementGuid>9eeedfcb-66a3-4504-83b4-9ed667d30e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Type'])[1]/following::th[1]</value>
      <webElementGuid>e9170d87-b44a-48f0-bfec-cda05c541551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Key'])[1]/following::th[2]</value>
      <webElementGuid>116d83ae-37a3-4bbb-8815-684aa86bcb4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Element Instance Key'])[2]/preceding::th[1]</value>
      <webElementGuid>e3ad5fbb-d3cb-4c25-bcf7-b3e0b4c0b7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[2]/preceding::th[2]</value>
      <webElementGuid>6b5c02cf-0b0b-4449-b54c-ad7f83cf9129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/thead/tr/th[4]</value>
      <webElementGuid>6fdf59ba-d424-4b3c-9b36-a465b08864f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Element' or . = 'Element')]</value>
      <webElementGuid>e89ae86b-e6cf-4f43-8c0b-6afc4a97eda8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs-:r0:--tabpanel-1']/div/table/thead/tr/th[2]</value>
      <webElementGuid>edfdad1d-8718-4592-8393-39c25cc1d0b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#'])[1]/following::th[1]</value>
      <webElementGuid>927d7ea5-6e10-4a86-bf09-ec6a445f8e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='global'])[1]/following::th[2]</value>
      <webElementGuid>99b6326c-9f6f-47ec-8547-b4c0bd38eeb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Element Instance Key'])[1]/preceding::th[1]</value>
      <webElementGuid>92993a56-3156-434f-a009-3bae022dc7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scope Key'])[2]/preceding::th[2]</value>
      <webElementGuid>cc5e830d-0c5b-4de5-8fae-7385b40d3699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Element']/parent::*</value>
      <webElementGuid>feffa18e-a44e-4ac2-8498-b27e484f71e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/thead/tr/th[2]</value>
      <webElementGuid>ad7a8f37-4c29-474d-8602-b75fdb8d7510</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
