<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Child Instance Key</name>
   <tag></tag>
   <elementGuidId>a8fa59a9-3a0a-4081-be79-76ff47ef99a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabs-:r0:--tabpanel-7']/div/table/thead/tr/th[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>b7da5931-e316-4995-8dfc-39744033e646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>2e4d25ca-ec71-4659-aabf-45d07b5df2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-6 py-3</value>
      <webElementGuid>c32c32d1-3e27-4caa-b0af-dfafab5c4e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Child Instance Key</value>
      <webElementGuid>a4e986df-f515-4474-8f55-6a17ac9b8447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs-:r0:--tabpanel-7&quot;)/div[@class=&quot;relative overflow-x-auto&quot;]/table[@class=&quot;w-full text-sm text-left&quot;]/thead[@class=&quot;text-base border-b-4 border-light-red&quot;]/tr[1]/th[@class=&quot;px-6 py-3&quot;]</value>
      <webElementGuid>3ca5b9f9-2ab1-4598-af9b-f13421717324</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs-:r0:--tabpanel-7']/div/table/thead/tr/th[2]</value>
      <webElementGuid>adfdb7b1-1ac2-4b85-a7a5-38ea42047cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#'])[8]/following::th[1]</value>
      <webElementGuid>ce7e7444-f72d-491c-9b3e-1a88546e1e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apple'])[20]/following::th[2]</value>
      <webElementGuid>1f1dc20a-dcfa-4a26-8bad-b5c0dd28b8d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Child BPMN Process Id'])[1]/preceding::th[1]</value>
      <webElementGuid>685eb185-026a-49c0-bd22-b61f736a5af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Element'])[7]/preceding::th[2]</value>
      <webElementGuid>e9a5ac9f-c625-41de-aa59-9f604961abb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Child Instance Key']/parent::*</value>
      <webElementGuid>58f72c70-91e2-4420-bb1f-7c82f582b5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/table/thead/tr/th[2]</value>
      <webElementGuid>21e06699-5e05-46ad-ab4e-dd7b47b0c185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Child Instance Key' or . = 'Child Instance Key')]</value>
      <webElementGuid>8f8ae682-c17b-48d8-a626-b276315a01ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
